### ISSUE TITLE
[Errata]: CanMV-K230_micropython_v0.3_sdk_v1.1_nncase_v2.4.0.img.gz连接CanMV IDE没有反应

### ISSUE THREAD

**Issue by icexiaoyou** [kendryte/k230_canmv_docs#1]
### Errata

按照官方指引，使用Etcher烧录了micropython镜像，装入K230开发板后，连接计算机，计算机的端口只显示两个主板CPU，且在IDE里面无法搜索到主板。
多次反复下载和烧录均不能成功连接。

**Comment by icexiaoyou** [comment]
![QQ截图20240118085106](https://github.com/kendryte/k230_canmv_docs/assets/95946934/eb0f467d-d7bc-4496-9e40-61c343c9016a)
![QQ截图20240118085125](https://github.com/kendryte/k230_canmv_docs/assets/95946934/77e55264-4fbb-415f-9bf4-bcd44b586ec2)

**Comment by wuwentao** [comment]
需要连接2个typeC的usb接口才行，如果只有2个串口，那就是只连接了一根线。
另外一个usb线也需要连接，并且出现三个串口，第三个串口是虚拟的micropython控制台串口，IDE能够自动搜索这个串口并连接成功。
因为没有连接usb线缆，所以没有第三个串口出现，ide软件报错属于正常结果。

**Comment by icexiaoyou** [comment]
稍后我会尝试。
那么，就是教程里面的“6 启动系统”的第一张图片，应该把POWER和USB一起连接电脑。
对于使用Micropython镜像，建议更新教程中的图片及表述。
【Link】
https://github.com/kendryte/k230_canmv_docs/blob/main/zh/CanMV-K230%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97.md
